total_timesteps: 100000
episode_len: 1000
train_env:
  env_name: SafeInvertedPendulumSwing-v0
  env_kwargs: {}
  num_env: ${num_env}

  
eval_env:
  env_name: SafeInvertedPendulumSwing-v0
  env_kwargs: {render_mode: rgb_array}
