# Main configuration file for SafeRL-Lib
# This file provides default settings and can be overridden by experiment configs

defaults:
  - experiments/SafetyAntVelocity_csac_lb  # Default experiment configuration (CSAC-LB)
  - _self_

# =============================================================================
# GLOBAL SETTINGS (can be overridden)
# =============================================================================
seed: 0
device: "cuda"
verbose: 1
save_freq: 100000
eval_freq: 1000
save_video_freq: 100000 
save_video: true
num_eval_episodes: 1
norm_obs: false
norm_act: true
norm_reward: true
norm_cost: false
num_env: 10
use_multi_process: false

# =============================================================================
# HYDRA CONFIGURATION
# =============================================================================
hydra:
  mode: RUN
  job:
    chdir: true
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/Benchmark/${env.train_env.env_name}/${algorithm.algorithm_name}/${seed}_${now:%H%M%S}/Seed${seed}_Cost${algorithm.model.cost_constraint}
  sweep:
    dir: ./exp/local/${now:%Y.%m.%d}/Benchmark/${env.train_env.env_name}/${algorithm.algorithm_name}/${seed}_${now:%H%M%S}
    subdir: ${hydra.job.num}_Seed${seed}_Cost${algorithm.model.cost_constraint}